<?php

return array (
  'ZERO' => 0,
  'ONE' => 1,
  'TWO' => 2,
  'ADMIN' => 'admin',
  'INDEX' => 'index',
  'ROLES' => 'roles',
  'PERMISSIONS' => 'permissions',
  'CR_SUCC' => 'created_successfully',
  'UD_SUCC' => 'updated_successfully',
  'DE_SUCC' => 'deleted_successfully',
  'ACT_FAIL' => 'action_failed',
  'TRUE' => true,
  'FALSE' => false,
  'MSG_SERVICE' => 'messages',
  'ACCOUNT_ACTIVATED' => 'account_activated',
  'ROLE_PERM_ASSIGN' => 'role_perm_assign',
  'USER_ROLE_PERM_DEL' => 'USER_ROLE_PERM_DEL',
  'CODE_RESENT' => 'code_resent',
  'RATE_LIMITED' => 'rate_limited',
  'SESSION_EXPIRED' => 'session_expired',
  'INVALID_CODE' => 'invalid_code',
  'UPDATE' => 'update',
  'TRY_AGAIN' => 'try_again',
  'HEE HEE' => 'hee hee',
);
